---
- name: Show SW vQFX Lab
  hosts: all
  gather_facts: no
  connection: netconf

  tasks:
    - name: Show
      junos_config:
        lines:
        - set cli screen-length 0
        - show vlans
