---
- name: Show SW vQFX Lab
  hosts: all
  gather_facts: no
  connection: netconf

  tasks:
    - name: run multiple commands on remote nodes
      junos_command:
         commands:
         - show version
         - show interfaces
      register: output
    - debug: var=output.stdout_lines
